# Generated by Django 5.2 on 2026-01-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('total_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='productsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('category', models.CharField(default='Other', max_length=50, verbose_name='Product Category')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productsmodel')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Products',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purshased_price', models.IntegerField(default=0)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productsmodel')),
            ],
        ),
    ]
