# Generated by Django 5.2 on 2026-01-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productsmodel_options_inbound_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousemodel',
            name='manager',
        ),
    ]
