# Generated by Django 5.2 on 2026-01-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_warehousemodel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehousemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbound',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehousemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product Name'),
        ),
    ]
