# Generated by Django 5.2 on 2026-01-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inbound_warehouse_outbound_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productsmodel'),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehousemodel'),
        ),
        migrations.AlterField(
            model_name='outbounditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productsmodel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(default='No Description', max_length=150),
        ),
    ]
