# Generated by Django 5.2 on 2026-01-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inbounditem_product_alter_outbound_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
