# Generated by Django 5.2 on 2026-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'operator'), ('manager', 'Manager')], default='operator', max_length=20),
        ),
    ]
