# Generated by Django 5.2 on 2026-01-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('manager', 'Manager')], default='operator', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('SYSTEM', 'System'), ('REPORT', 'Report')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_model', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Report',
                'verbose_name_plural': 'Activity Reports',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['-performed_at'], name='users_repor_perform_de8f12_idx'), models.Index(fields=['user'], name='users_repor_user_id_4f21d7_idx'), models.Index(fields=['activity'], name='users_repor_activit_6d00bf_idx'), models.Index(fields=['object_model'], name='users_repor_object__203f39_idx')],
            },
        ),
    ]
