# Generated by Django 5.2 on 2026-01-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_role_reportmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='warehouse',
        ),
    ]
