# Generated by Django 5.2 on 2026-01-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_warehousemodel_manager'),
        ('users', '0005_remove_usermodel_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousemodel'),
        ),
    ]
