# Generated by Django 5.2 on 2026-01-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermodel_warehouse'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
